### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by Leptopoda**
This PR introduces linting with the [lints](https://pub.dev/packages/lint) package.

It is based on #168

### CODE REVIEW

**Comment by Teifun2** [comment]
I Think this branch needs to be rebased on your new null-safety implementation :D

**Comment by Leptopoda** [comment]
It's been rebased the entire time; just needed a push :)

**Comment by Teifun2** [comment]
Jesus you are FAAAST :D

**Review by Teifun2 — APPROVED** [review]

**Comment by Teifun2** [comment]
Thanks a lot for these additions!

**Pull request merged**
