### PR TITLE
Feature/v1.1.0

### PR DESCRIPTION
**Pull request by Leptopoda**
Support api 0.1.1 as on the latest master.

As announced in the cookbook matrix the api endpoint will probably also change thus marking as draft so we cna merge once the new api is out :)

### CODE REVIEW

**Comment by Croydon** [comment]
May I ask what the current state of this PR is? Apparently the new API got released, basically breaking the entire app right now

**Comment by Leptopoda** [comment]
The pr is done it's just that further breaking changes where announced so I wanted to wait for them.

Seeing the new cookbook release I'll test once more and mark this as ready for review.

Just give me a few hours 🙃

**Comment by Leptopoda** [comment]
Ok I just looked into it and the other changes did not land yet so in theory the PR is ready to go.

The only porblem is that the internal representation of the recipeId changed and thus if you update the app while still having timers running in the background we'll fail and the app will go into a crash loop.

I'll need to handle this case. Otherwise feel free to compile and run :)

**Review by Teifun2 — APPROVED** [review]
So if i understand this correct. The only changes of the API are to the data structure not the actual api calls. Is that correct?

**Review by Teifun2 — APPROVED** [review]

**Comment by Leptopoda** [comment]
To be correct the data structure didn't change as the old spec said the id is a string and it was just a bug in the server that an int was returned.

I mean the server didn't comply to its own spec.

Christian announced on matrix that the api calls would also change (the new api would be served under v2 but that didn't land) and was the reason it was still a draft.

**Comment by Teifun2** [comment]
@Leptopoda perfect thanks for the clarification. Sorry for not following the news myself, and thanks for your continued contribution.

**Comment by Teifun2** [comment]
@Leptopoda Would it make sense to release this version?

**Comment by Leptopoda** [comment]
Obviously yes

It's needed to make the app working again.

Although a minor release might be enough

**Comment by Leptopoda** [comment]
@Teifun2 
So I just asked christian again and they just said they'll still make the changes to the api so further breaking changes will come.

Nevertheless I still think you should make a release for now so we get a working release out.

**Pull request merged**
