### PR TITLE
Null safety

### PR DESCRIPTION
**Pull request by Leptopoda**
Should be ready to go :)

### CODE REVIEW

**Review by Teifun2 — APPROVED** [review]
Wow this is awesome thank you very much!

**Comment by Teifun2** [comment]
There is an issue with the build. 

Supposedly this is due to the gradle version number. 
It is suggested to increase the version to

_classpath "com.android.tools.build:gradle:7.1.3"_ 

In the file build.gradle

**Comment by Leptopoda** [comment]
Looks more like a nullability error to me
https://github.com/Teifun2/nextcloud-cookbook-flutter/actions/runs/3807469951/jobs/6485346462#step:6:20

Although the attribute in question is not nullable and it builds fine on my machine :thinking:
On the latest version of flutter_notifications the field is nullable ...
I'll upgrade it to 13.0.0 later :)

**Comment by Leptopoda** [comment]
Ok looks like I accidentally changed the local cache of my dependencies and `flutter clean` only pruned the build cache so the deps wouldn't be fetched again.

`flutter bup clean` did the job and I added a null-check in that place. As I already upgraded the deps though It's also included now.

**Comment by Teifun2** [comment]
Wow that was fast! Thanks!

**Review by Teifun2 — APPROVED** [review]

**Pull request merged**
