### PR TITLE
add some basic ci configuration

### PR DESCRIPTION
**Pull request by Mic92**
untested. Let's see if it builds.

### CODE REVIEW

**Comment by Teifun2** [comment]
Thanks for starting this! Should this be merged now to check that the basic debug build action works? or do you want to add the uploading of apks before that?

**Comment by Mic92** [comment]
You can merge this as it is. Uploading APKs needs be done in a seperate github action, which is only triggered on releases so there is a release tag where files can be uploaded to.

**Comment by Mic92** [comment]
Here is a successful run: https://github.com/Mic92/nextcloud-cookbook-flutter/runs/910575712?check_suite_focus=true

**Comment by Teifun2** [comment]
Thanks for your help!

**Pull request merged**
